[package]
name = "jni"
version = "0.1.0"
edition = "2021"
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
core = { path = "../core" }
http = { path = "../http" }
messaging = { path = "../messaging" }
tls = { path = "../tls" }
jni = "0.21"
base64 = "0.22"

[lib]
name = "modernlink"
crate-type = ["cdylib"]
